name: flutter_ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  
  # State Management

  #Hooks
  flutter_hooks: ^0.20.5

  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # LOCAL ASSETS
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/images/on_boarding_images/sammy-line-delivery.gif
    - assets/images/on_boarding_images/sammy-line-no-connection.gif
    - assets/images/on_boarding_images/sammy-line-searching.gif
    - assets/images/on_boarding_images/sammy-line-shopping.gif
    - assets/logos/
    - assets/logos/t-store-splash-logo-black.png
    - assets/logos/t-store-splash-logo-white.png
    - assets/logos/google-icon.png
    - assets/logos/facebook-icon.png

  # LOCAL FONTS
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

