name: flutter_ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  url_launcher: ^6.3.1

  # Old Program
  asp: ^2.0.3
  dio: ^5.7.0
  flutter_modular: ^6.3.4 #flutter modular
  fquery: ^1.4.0-beta.1
  go_router: ^13.0.0 # Deep Links
  google_sign_in: ^6.2.2 # Google
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # Product Specific
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  
  # State Management

  #Hooks
  flutter_hooks: ^0.20.5

  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # LOCAL ASSETS
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/on_boarding_images/sammy-line-delivery.gif
    - assets/images/on_boarding_images/sammy-line-no-connection.gif
    - assets/images/on_boarding_images/sammy-line-searching.gif
    - assets/images/on_boarding_images/sammy-line-shopping.gif
    - assets/images/products/
    - assets/logos/
    - assets/logos/t-store-splash-logo-black.png
    - assets/logos/t-store-splash-logo-white.png
    - assets/logos/google-icon.png
    - assets/logos/facebook-icon.png

  # LOCAL FONTS
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

